### PR TITLE
Add control over idle settings (requires Spark 3.0.0 or later)

### PR DESCRIPTION
**Pull request by Plyha**
https://github.com/igniterealtime/Spark/pull/674

### CODE REVIEW

**Comment by guusdk** [comment]
I'm not seeing a problem, but the description is pretty confusing to me. I'd suggest changing it to:

> Allow users to modify the 'idle' settings in the "Login" menu item.

I would not mention what the default configuration is (which users will have to use if the feature is disabled), because if that default ever changes in Spark, then this description is wrong. Alternatively, we can add a feature to this plugin that explicitly sets the values used by the clients.

**Comment by guusdk** [comment]
Also: please add an entry to the changelog file.

**Comment by Plyha** [comment]
If I understood you correctly, you want the logic to be like this:

client.features.idleonlock                       = Modify Idle 
client.features.idleonlock.description           = Allow users to modify the 'idle' settings in the "Appearance" menu item.


client.features.idletimelock                       = Default Idle Settings
client.features.idletimelock.description           = Set default idle settings used by the clients

do not look at the name of the variables, I will rewrite the logic :D

**Comment by Plyha** [comment]
I got you. Remade. What do you think of it?

**Pull request merged**
